version: "2.3"

################################################################################

services:
  jupyter:
    hostname: jupyter
    runtime: ${DOCKER_RUNTIME}
    privileged: true
    environment:
      # Display X Server GUI.
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      # Configure Nvidia Docker interface.
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_REQUIRE_CUDA=cuda>=8.0
      # Configure PulseAudio interface.
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    build:
      context: ../
      dockerfile: ./jupyter_docker/Dockerfile
    volumes:
      # Map repository sources.
      - ../:/root/jupyter_playground/
      # Grant display access to X Server.
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Grant audio access to PulseAudio.
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
    network_mode: host
    command: /root/jupyter_playground/jupyter_docker/scripts/initialize-docker-container.sh
